name: Design System Contribution
description: Contribute to Atlas Design System
title: "[DS]: "
labels: "design-system"
body:
- type: input
  id: summary
  attributes:
    label: Summary
    description: "What would you like to have done?"
    placeholder: "I need a new icon, or I need a new component"
  validations:
    required: true
- type: markdown
  value: "## Welcome!"
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord.
