name: Design system contribution idea
description: Contribute to the Atlas Design System
assignees: "toiletgranny"
labels: "design-system"
body:
- type: textarea
  id: description
  attributes:
    label: Description
    description: "Give us a little context around your contribution idea."
  validations:
    required: true
- type: input
  id: component-link
  attributes:
    label: Component in Figma
    description: "If this is about an existing component, provide a Figma link"
    placeholder: "https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=..."
  validations:
    required: false
- type: dropdown
  id: priority
  attributes:
    label: How important this is to you?
    options:
      - "It's blocking me right now"
      - "This will block me soon"
      - "Not a blocker, but still worth considering"
  validations:
    required: true
