name: Design System Contribution
description: Contribute to Atlas Design System
title: "[DS]: "
labels: "design-system"
body:
- type: input
  id: summary
  attributes:
    label: Summary
    description: "What would you like to have done?"
    placeholder: "I need a new icon, or I need a new component"
  validations:
    required: true
- type: markdown
  value: "Additional context for your request!"
