name: Design System Contribution
description: Contribute to Atlas Design System
title: "[DS]: "
labels: "design-system"
body:
- type: input
  id: summary
  attributes:
    label: Summary
    description: "What would you like to have done?"
    placeholder: "I need a new icon, or I need a new component"
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Description
    description: "Give us a little context around your contribution idea."
  validations:
    required: true
- type: dropdown
  id: priority
  attributes:
    label: How important this is to you?
    options:
      - "It's blocking me right now"
      - "This will block me soon"
      - "Not a blocker, but still worth considering"
  validations:
    required: true
